version: '3.9'

services:
  eclaireur-public-psql:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=eclaireur_public
      - POSTGRES_DB=eclaireur_public
