workflow:
  save_to_db: False
  replace_tables: False

ofgl:
  data_folder: back/data/ofgl
  urls_csv: back/scripts/datasets/ofgl_urls.csv
  combined_filename: back/data/ofgl/ofgl.parquet

communities:
  data_folder: back/data/communities
  combined_filename: back/data/communities/communities.parquet
  epci_url: https://www.collectivites-locales.gouv.fr/files/Accueil/DESL/2025/epcicom2025-2.xlsx
  odf_url: file:./back/scripts/datasets/odf.csv

  geolocator:
    epci_coords_scrapped_data_file: back/data/communities/scrapped_data/geoloc/epci_geolocs.csv
    reg_dep_coords_scrapped_data_file: back/data/communities/scrapped_data/geoloc/dep_reg_centers.csv
    geolocator_api_url: https://api-adresse.data.gouv.fr/search/csv/
    temp_folder:
      path: back/data/communities/processed_data
      filename: cities_to_geolocate.csv

datagouv:
  datasets:
    url: https://www.data.gouv.fr/fr/datasets/r/f868cca6-8da1-4369-a78d-47463f19a9a3
    columns:
      - "id"
      - "title"
      - "url"
      - "description"
      - "organization"
      - "organization_id"
      - "frequency"
  datafiles:
    url: https://www.data.gouv.fr/fr/datasets/r/4babf5f2-6a9c-45b5-9144-ca5eae6a7a6d
  paths:
    root: back/data/datagouv_search
    organization_datasets: organization_datasets
  files:
    catalog: datagouv_catalog.parquet
    catalog_metadata: catalog_metadata.parquet
    datasets: datagouv_datasets.parquet

search:
  subventions:
    source: "multiple"
    title_filter: (?:conventions de subvention|subv.*asso|subvention.*association|Subventions du Conseil Régional|Interventions de la Région des Pays de la Loire|SCDL - Subventions)
    description_filter: (?:conventions de subvention|subvention.*association|subv.*asso)
    api:
      testIds: [] # use full input
      url: "https://www.data.gouv.fr/api/1/datasets/"
      title:
        - "association"
        - "subvention"
        - "intervention"
        - "aide"
        - "versement"
      description:
        - "association"
        - "subvention"
        - "intervention"
        - "aide"
        - "versement"
      columns:
        - "montant"
    schema:
      url: "https://schema.data.gouv.fr/schemas/scdl/subventions/2.1.0/schema.json"
    single_urls_file: back/data/datasets/subventions/inputs/single_urls.csv
    schema_dict_file: back/data/datasets/subventions/inputs/dataset_dict.csv

marches_publics:
  schema: "https://schema.data.gouv.fr/schemas/139bercy/format-commande-publique/1.5.0/marches.json"
  data_folder: back/data/marches_publics
  combined_filename: back/data/marches_publics/marches_publics.parquet
  test_urls: null

datagouv_catalog:
  data_folder: back/data/datagouv_catalog
  combined_filename: back/data/datagouv_catalog/catalog.parquet
  catalog_url: null
  
datafile_loader:
  data_folder: 'back/data/datasets/%(topic)s'
  combined_filename: 'back/data/datasets/%(topic)s.parquet'
  file_info_columns:
    - "siren"
    - "organization"
    - "title"
    - "created_at"
    - "url"
    - "nom"
    - "type"
    - "source"

file_age_to_check:
  files:
    odf_data: back/data/communities/processed_data/odf_data.csv
    ofgl_data: back/data/communities/processed_data/ofgl_data.csv
  age: 365

elected_officials:
  data_folder: back/data/elected_officials

sirene:
  data_folder: back/data/sirene
  combined_filename:  back/data/sirene/sirene.parquet
  url: https://files.data.gouv.fr/insee-sirene/StockUniteLegale_utf8.zip

datagouv_api:
  organization_folder: back/data/datagouv_api/organizations

declarations_interet:
  data_folder: back/data/declarations_interet
  url: https://www.data.gouv.fr/fr/datasets/r/247995fb-3b98-48fd-95a4-2607c8a1de74

financial_accounts:
  data_folder: back/data/financial_accounts
  files_csv: back/scripts/datasets/communities_financial_accounts.csv
  columns_mapping: back/scripts/datasets/normalization_financial_account_columns.csv
  combined_filename: back/data/financial_accounts/financial_accounts.parquet

outputs_csv:
  path: 'back/data/datasets/%(topic)s/outputs'

warehouse:
  data_folder: back/data/warehouse

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: simple
      filename: back/data/logs/log.txt
  loggers:
    back:
      level: INFO
      handlers: [console, file]