workflow:
  save_to_db: True
  replace_tables: True

ofgl:
  data_folder: back/tests/data/ofgl
  urls_csv: back/tests/inputs/ofgl_urls_ci.csv
  combined_filename: back/tests/data/ofgl/ofgl.parquet

communities:
  combined_filename: back/tests/data/communities/communities.parquet
  epci_url: https://www.collectivites-locales.gouv.fr/files/Accueil/DESL/2025/epcicom2025-2.xlsx
  odf_url: file:./back/scripts/datasets/odf.csv

  geolocator:
    epci_coords_scrapped_data_file: back/data/communities/scrapped_data/geoloc/epci_geolocs.csv
    reg_dep_coords_scrapped_data_file: back/data/communities/scrapped_data/geoloc/dep_reg_centers.csv
    geolocator_api_url: https://api-adresse.data.gouv.fr/search/csv/
    temp_folder:
      path: back/tests/data/geolocator/
      filename: cities_to_geolocate.csv

  postal_code:
    url: https://www.data.gouv.fr/fr/datasets/r/170ec28c-cd4a-4ce4-bac5-f1d8243cd7bb

datagouv:
  datasets:
    url: https://www.data.gouv.fr/fr/datasets/r/f868cca6-8da1-4369-a78d-47463f19a9a3
    columns:
      - "id"
      - "title"
      - "url"
      - "description"
      - "organization"
      - "organization_id"
      - "frequency"
  datafiles:
    url: "file:./back/tests/inputs/datagouv-datafiles-10000.csv"
  paths:
    root: back/tests/data/datagouv_search
    organization_datasets: organization_datasets
  files:
    catalog: datagouv_catalog.parquet
    catalog_metadata: catalog_metadata.parquet
    datasets: datagouv_datasets.parquet

search:
  subventions:
    source: "multiple"
    title_filter: (?:conventions de subvention|subv.*asso|subvention.*association|Subventions du Conseil Régional|Interventions de la Région des Pays de la Loire|SCDL - Subventions)
    description_filter: (?:conventions de subvention|subvention.*association|subv.*asso)
    api:
      testIds:
        - 534fffa7a3a7292c64a780c5
        - 534fffada3a7292c64a780f9
      url: "https://www.data.gouv.fr/api/1/datasets/"
      title:
        - "association"
        - "subvention"
        - "intervention"
        - "aide"
        - "versement"
      description:
        - "association"
        - "subvention"
        - "intervention"
        - "aide"
        - "versement"
      columns:
        - "montant"
    schema:
      url: "https://schema.data.gouv.fr/schemas/scdl/subventions/2.1.0/schema.json"
    single_urls_file: back/tests/inputs/single_urls_2.csv
    schema_dict_file: back/data/datasets/subventions/inputs/dataset_dict.csv

marches_publics:
  schema: "https://schema.data.gouv.fr/schemas/139bercy/format-commande-publique/1.5.0/marches.json"
  data_folder: back/tests/data/marches_publics
  combined_filename: back/tests/data/marches_publics/marches_publics.parquet
  test_urls:
    - url: file:./tests/back/loaders/fixtures/reduced_decp_2019.json
    - format: json

datagouv_catalog:
  data_folder: back/tests/data/datagouv_catalog
  combined_filename: back/tests/data/datagouv_catalog/catalog.parquet
  catalog_url: file:./back/tests/inputs/datagouv_catalog.csv

datafile_loader:
  data_folder: 'back/tests/data/datasets/%(topic)s'
  combined_filename: 'back/tests/data/datasets/%(topic)s.parquet'
  file_info_columns:
    - "siren"
    - "organization"
    - "title"
    - "created_at"
    - "url"
    - "nom"
    - "type"
    - "source"

file_age_to_check:
  files: {}
  age: 365


elected_officials:
  data_folder: back/tests/data/elected_officials

sirene:
  data_folder: back/tests/data/sirene
  combined_filename: back/tests/data/sirene/sirene.parquet
  url: file:./tests/back/datasets/fixtures/StockUniteLegale_utf8.zip

datagouv_api:
  organization_folder: back/tests/data/datagouv_api/organizations

declarations_interet:
  data_folder: back/tests/data/declarations_interet
  url:  file:./tests/back/datasets/fixtures/declaration.xml

financial_accounts:
  data_folder: back/tests/data/financial_accounts
  files_csv: back/tests/inputs/ci_communities_financial_accounts.csv
  columns_mapping: back/scripts/datasets/normalization_financial_account_columns.csv
  combined_filename: back/tests/data/financial_accounts/financial_accounts.parquet

outputs_csv:
  path: 'back/tests/data/datasets/%(topic)s/outputs'

warehouse:
  data_folder: back/tests/data/warehouse

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: simple
      filename: back/tests/data/logs/log.txt
  loggers:
    back:
      level: INFO
      handlers: [console, file]