name: 'Deploy Data'
description: 'Run the data pipeline'

inputs:
  db_host:
    description: 'Database host'
    required: true
  db_name:
    description: 'Database name'
    required: true
  db_user:
    description: 'Database user'
    required: true
  db_password:
    description: 'Database password'
    required: true
  db_port:
    description: 'Database port'
    required: true
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.13'

runs:
  using: 'composite'
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'poetry'

    - name: Install dependencies
      shell: bash
      run: poetry install

    - name: Run data pipeline
      shell: bash
      run: poetry run python back/main.py
      env:
        DB_HOST: ${{ inputs.db_host }}
        DB_NAME: ${{ inputs.db_name }}
        DB_USER: ${{ inputs.db_user }}
        DB_PASSWORD: ${{ inputs.db_password }}
        DB_PORT: ${{ inputs.db_port }}
