name: test-run

on:
  pull_request:
  push:
    branches: [main]
    paths-ignore:
      - "data-analyst/**"
      - "front/**"
      - "node_modules/**"
      - "yarn.lock"
      - ".gitignore"
      - ".github/workflows/review.yml"

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install poetry and dependencies
      run: |
        python -m pip install poetry
        poetry install
    - name: Docker compose (start postgres)
      run: docker compose -f docker-compose.yaml up -d
    - name: Run pipeline
      run: |
        poetry run python back/main.py -f back/config-test.yaml
